# -*- coding: utf-8 -*-
"""shaily.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RQidfqCLrjZM8VT9kc4CbY_0TVrDAaJm
"""

# python program to square the elements of a list

def square_num(n):
  return n * n
nums = [4, 5, 2, 9]
print("Original List: ",nums)
result = map(square_num, nums)
print("Square the elements of the list using map():")
print(list(result))

# python program to triple all numbers of a given list of integers

nums = (1,2,3,4,5,6,7)
result = map(lambda x:x + x + x, nums)
print(list(result))

# python program to create a lambda function that adds 25 to a given number passed in as an argument

r = lambda a : a + 25
print(r(10))

